image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Contiki OS
    init: |
      cd $HOME
      git clone https://github.com/contiki-os/contiki.git
      cd contiki
      git submodule update --init
    command: |
      echo "Contiki OS setup completed successfully!"

  - name: Install dependencies
    command: |
      sudo apt-get update
      sudo apt-get install -y build-essential openjdk-11-jdk ant git python2.7 python3 python3-pip wget unzip
      sudo ln -sf /usr/bin/python2.7 /usr/bin/python2

  - name: Build Cooja
    command: |
      cd $HOME/contiki/tools/cooja
      ant jar
      echo "Cooja simulator built successfully"

vscode:
  extensions:
    - ms-vscode.cpptools
